[project]
name = "default"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.7",
    "jupyterlab-lsp>=5.2.0",
    "jupytext>=1.17.3",
    "pip>=25.2",
]

[dependency-groups]
dev = [
    "basedpyright>=1.32.1",
]
